### ISSUE TITLE
Rollup compatible?

### ISSUE THREAD

**Issue by deamme** [gcanti/redux-tcomb#1]
Can this module be made rollup compatible just like [redux](https://github.com/rackt/redux)? https://github.com/rollup/rollup/wiki/jsnext:main

**Comment by gcanti** [comment]
Hi!
Didn't know that, thanks for pointing out.
redux-tcomb is written is ES5, what should I do in order to be rollup compatible?

**Comment by deamme** [comment]
Hmm, maybe you can't.. It can't really be written to ES6 because of tcomb right?

**Comment by gcanti** [comment]
Honestly I don't know, it's the first time I hear of jsnext (and the tcomb library is written is ES5 as well)

**Comment by deamme** [comment]
I guess everything needs to be rewritten in ES6 then. Seems like a lot of work at first but I think it can be done pretty easily with another workflow. I'll try look more into it..

**Comment by clintwood** [comment]
+1 Ideally I'd like the same, maybe @Rich-Harris can briefly chime in for some direction?
