### ISSUE TITLE
createActionType should be using payload

### ISSUE THREAD

**Issue by danielkcz** [gcanti/redux-tcomb#13]
It's somewhat confusing that data you pass in action dispatch are merged together with type of the action. I think that those data should go to `payload` property instead. This is especially important when my TcombType actually has it's own `type` property denoting something else. In that case it would fail with this:

`TypeError: [tcomb] Invalid call to mixin(target, source, [overwrite]): cannot overwrite property "type" of target object`

**Comment by gcanti** [comment]
> I think that those data should go to `payload` property instead

What if you define flux standard actions? You need more than a `payload` property. The shape of an action should be freely defined by the user, not imposed by this library

**Comment by danielkcz** [comment]
Well, the `payload` is part of FSA, it's optional, but definitely not something that would be against that standard. I kinda like this part of standard rather then mixed values and unable to use simple `type` property.

You certainly agree that error popping there is not good thing. Perhaps it could be optional behavior you can specify for `createActionType` call? Something like `createActionType(actions, { usePayload: true })`.

If I would have to specify payload for each of my action, it suddenly becomes very verbose to define those actions and `createActionType` kinda loses part of its magic brilliance.

**Comment by gcanti** [comment]
I meant: the general shape of an FSA is

``` js
type FSA = {
  type: string,
  payload?: any,
  error?: boolean,
  meta?: any
};
```

so this library can't assume a single `payload` property. 

Some users might not follow FSA and probably they want to define their actions without restrictions.

Also, it's pretty easy to define a wrapper of `createActionType` with your own logic

**Comment by danielkcz** [comment]
So you mean like iterating over those actions and wrap everything into `t.interface({ payload: type })`? I guess that could be a way, but feels rather dirty with too much wrapping for my taste.

I don't understand why it cannot be optional behavior to use `payload`, but I think I will just copy&paste the `createActionType` and modify for my needs. It's not that big to be a problem.
