### ISSUE TITLE
createActionType should export actionCreators

### ISSUE THREAD

**Issue by danielkcz** [gcanti/redux-tcomb#14]
I would love to use it together with `bindActionCreators` of Redux. Currently these are mixed into returned type and there is no easy way to extract them.

**Comment by gcanti** [comment]
Something like

``` js
function createActionType(actions) {
  ...
  Action.actionCreators = actionCreators // <= export actionCreators
  t.mixin(Action, actionCreators);
  return Action;
}
```

**Comment by danielkcz** [comment]
Yes, sounds good enough for sure.

**Comment by gcanti** [comment]
Ok. Would you like to send a PR?

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/redux-tcomb/releases/tag/v0.2.1, thanks @FredyC
