### ISSUE TITLE
createReducer breaks if used in Redux.combineReducers(...)

### ISSUE THREAD

**Issue by clintwood** [gcanti/redux-tcomb#2]
When using `Redux.combineReducers(...)` with automatically generated reducers from a call to `createReducer(...)` a type error something like this is generated:
`TypeError: [tcomb] Unknown action type m.7.p.f.c.p.z.x.g.v.i for union Action`.

This is because when Redux combines reducers it probes all reducers to be combined with a randomly generated action type to ensure each reducer returns `undefined` for action types that should be unrecognized by reducers.  I think your `isReduxAction(...)` check is not catching this and I'm not sure how it could!

**Comment by gcanti** [comment]
Hi @clintwood
Thanks for your detailed issue.

> This is because when Redux combines reducers it probes all reducers to be combined with a randomly generated action type

That is really weird. Reading the source the format is:

``` js
var type = Math.random().toString(36).substring(7).split('').join('.');
```

> I think your isReduxAction(...) check is not catching this and I'm not sure how it could!

A clean solution would be adding the namespace `"@@redux/"` to the randomly generated action type (like in redux's `ActionTypes.INIT`).
Maybe we should open an issue on [redux](https://github.com/rackt/redux).

A dirty solution would be detecting the `"m.7.p.f.c.p.z.x.g.v.i"` format in the `isReduxAction` predicate or using a copy of `combineReducers` without those checks.

**Comment by clintwood** [comment]
@gcanti, yup, I actually hit this before and debugged through to that line.  Agreed it should really be prefixed because it is completely out of band with the `@@redux/` prefixes which denote redux specific internal actions.

I think the dirty solution will break at some point if/when the redux folk decide to change internal implementations.

I think it makes sense for you to raise this issue with the redux folk, since it prohibits safety checks in libraries like this!

**Comment by gcanti** [comment]
Hi @clintwood

I submitted a PR to redux with a fix. 
In the meanwhile I just published a temporary (and ugly) fix in https://github.com/gcanti/redux-tcomb/releases/tag/v0.1.5

**Comment by clintwood** [comment]
Awesome I saw that! Thanks for the quick turnaround!
