### ISSUE TITLE
Make action type-checking optional?

### ISSUE THREAD

**Issue by Enet4** [gcanti/redux-tcomb#6]
In my project, actions are created using action constructors. Given that these are properly invoked and implemented, type-checking the resulting actions is unnecessary and would have demanded for a complete (exhausting) definition of all actions.

Could this library be adjusted so as to make action type-checking optional? As in, being able to pass `null` or `undefined` to the `Action` argument of `getCheckedReducer`?

**Comment by gcanti** [comment]
If I understand correctly, you just want to type-check the `State` right? It's definitely possible

**Comment by gcanti** [comment]
You can pass `t.Any` as third argument of `getCheckedReducer` (`t.Any` represents the type of all possible values)

**Comment by Enet4** [comment]
Ah, good thinking, I'll try that. Thanks.
