### ISSUE TITLE
Is there an example of using a tcomb generated reducer and combineReducers?

### ISSUE THREAD

**Issue by zpratt** [gcanti/redux-tcomb#7]
I'm attempting to utilize the automatically generated reducer with `combineReducers` using the latest version of redux-tcomb and redux. When calling redux's `combineReducers`, I'm getting an error. From looking over the issues for this project, it appears that this should be possible based on a PR that was done for redux. I get an error thrown that says `path.join is not a function` which originates from Struct in tcomb (our state is a Struct). Is there an example of how to do this?

**Comment by gcanti** [comment]
Hi,

Could you please post a minimal example reproducing the error?

**Comment by zpratt** [comment]
@gcanti thanks for the quick response. I was able to make it past the issue I was having with the `path.join` error by changing the way I was calling `combineReducers`. However, now I've run into an issue where I cannot publish actions that are not specified by the action union.

Minimal example located here: https://tonicdev.com/zpratt/redux-tcomb-example

My real world use case is that I want to use redux-tcomb with the redux-simple-router and I get errors with a I dispatch [pushPath](https://github.com/rackt/redux-simple-router#pushpathpath-state--avoidrouterupdate--false---) since it publishes a redux-simple-router specific action and tcomb doesn't have a corresponding action defined in the union.

I think it would be useful to have an example of how to use `combineReducers` here. Once we figure this out, I'll provide a PR to capture how to wire it all up.

**Comment by gcanti** [comment]
The point of `redux-tcomb` is to ensure type safety, hence the raised error is expected: the `other` action is not recognized so `redux-tcomb` thinks it's a development error. I see 2 solution:
1. Maintaining strong type safety (suggested): add the `other` action to `Actions`

``` js
var Other = t.struct({
    wizards: t.list(t.String)
});

Other.prototype.patch = function (state) {
  return state;
};

var Actions = createUnion({
    AddName: AddName,
    DeleteNames: DeleteNames,
    other: Other
});

....
```
1. Decrease type safety: ignore not recognized actions

``` js
var typeCheckedActions = {
    AddName: AddName,
    DeleteNames: DeleteNames
};

var Actions = createUnion(typeCheckedActions);

// dummy action
var Dummy = t.struct({});
// patch is just the identity
Dummy.prototype.patch = function (state) { return state; };

// override the default union type dispatch
var defaultDispatch = Actions.dispatch;
Actions.dispatch = function (action) {
  return typeCheckedActions.hasOwnProperty(action.type) ? defaultDispatch(action) : Dummy;
};

...
```

**Comment by zpratt** [comment]
I think I've got my answers for my initial topic. I propose that we close this issue an open another issue to discuss how to integrate 3rd party actions (like the `pushPath` action that comes with the redux-simple-router). Thoughts?
