### ISSUE TITLE
Question: Is new state type checked?

### ISSUE THREAD

**Issue by dcworldwide** [gcanti/redux-tcomb#8]
Hi, great library. I just have a general question which I didn't understand from the readme. I'm talking specifically about the Standard Reducer approach. 

I understand that type checking is applied when dispatching actions. But what about the state returned by a reducer? If yes, I'm assuming type checking is applied to the entire state tree? Which seems expensive if you've only just updated 1 element in an array..

Thanks

**Comment by gcanti** [comment]
Hi,

> Which seems expensive 

Type checking will run only in development:

https://github.com/gcanti/redux-tcomb/blob/master/lib/getCheckedReducer.js#L14

**Comment by dcworldwide** [comment]
Thanks @gcanti 

Ok got it. Type checks are applied to state returned by reducers, but only during a dev build. That's great thanks.
